### ISSUE TITLE
MS-CHAPv2 with gluu-radius

### ISSUE THREAD

**Issue by timur32** [GluuFederation/radius#53]
Hello! 
I'm trying to setup gluu-server as 2FA for microsoft services using MS NPS. But NPS using MS-CHAP and in log files I see next:
`[ERROR] 2020-07-26 17:48:24.696 [Radius Auth Listener] RadiusServer - malformed Radius packet
org.tinyradius.util.RadiusException: Access-Request: User-Password or CHAP-Password/CHAP-Challenge missing
        at org.tinyradius.packet.AccessRequest.decodeRequestAttributes(AccessRequest.java:160) ~[tinyradius-1.0.jar:?]
        at org.tinyradius.packet.RadiusPacket.decodePacket(RadiusPacket.java:889) ~[tinyradius-1.0.jar:?]
        at org.tinyradius.packet.RadiusPacket.decodeRequestPacket(RadiusPacket.java:538) ~[tinyradius-1.0.jar:?]
        at org.tinyradius.util.RadiusServer.makeRadiusPacket(RadiusServer.java:459) ~[tinyradius-1.0.jar:?]
        at org.tinyradius.util.RadiusServer.listen(RadiusServer.java:328) [tinyradius-1.0.jar:?]
        at org.tinyradius.util.RadiusServer.listenAuth(RadiusServer.java:277) [tinyradius-1.0.jar:?]
        at org.tinyradius.util.RadiusServer$1.run(RadiusServer.java:103) [tinyradius-1.0.jar:?]
`
I understood that gluu-radius expect only PAP ( login + password ). Is that right?
Do I have any chance of making it work?
Can I disable check password in gluu-radius at all? I need only second factor (push notice in supergluu) from gluu. First factor is my MS AD. 
Thanks in advance.

**Comment by nynymike** [comment]
You'll need to register and post this question on https://support.gluu.org 

We do not provide any support on Github.
